name: Bug 报告
description: 发起 bug 报告
body:
  - type: markdown
    attributes:
      value: |
        在报告问题之前，请确保您已经 **认真** 想过
  - type: input
    id: bs
    attributes:
      label: Minecraft 版本
    validations:
      required: true
  - type: dropdown
    id: minecraft-launcher
    attributes:
      label: 您正在使用的 Minecraft Launcher
      options:
        - HMCL
        - PCL2
        - BakaXL
  - type: textarea
    id: what-happened
    attributes:
      label: 出现了什么问题？
      description: 顺便告诉我们，您期望的行为是怎样的？
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 错误日志
      description: 您可以粘贴 Minecraft 的日志
      render: text
  - type: textarea
    id: reproduction
    attributes:
      label: 重现步骤
      description: 详细描述您出错前的操作步骤
    validations:
      required: true
