
blank_issues_enabled: false
contact_links:
  - name: 启动器建议
    url: https://github.com/jdnjk/Monday/discussions/categories/%E5%90%AF%E5%8A%A8%E5%99%A8%E5%BB%BA%E8%AE%AE
    about: 发点建议投票
  - name: 询问关于使用 Blessing Skin 的问题
    url: https://github.com/jdnjk/Monday/discussions
    about: 如果要报告 bug,选择此项
